// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.quxionglie.rpc.protobuf3.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string img = 3;</code>
     */
    String getImg();
    /**
     * <code>optional string img = 3;</code>
     */
    com.google.protobuf.ByteString
        getImgBytes();

    /**
     * <code>optional string mobile = 4;</code>
     */
    String getMobile();
    /**
     * <code>optional string mobile = 4;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>optional uint64 createAt = 7;</code>
     */
    long getCreateAt();

    /**
     * <code>optional int32 communityId = 5;</code>
     */
    int getCommunityId();

    /**
     * <code>optional string communityName = 6;</code>
     */
    String getCommunityName();
    /**
     * <code>optional string communityName = 6;</code>
     */
    com.google.protobuf.ByteString
        getCommunityNameBytes();
  }
  /**
   * Protobuf type {@code tutorial.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0;
      name_ = "";
      img_ = "";
      mobile_ = "";
      createAt_ = 0L;
      communityId_ = 0;
      communityName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              img_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 40: {

              communityId_ = input.readInt32();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              communityName_ = s;
              break;
            }
            case 56: {

              createAt_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserProto.internal_static_tutorial_User_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserProto.internal_static_tutorial_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              User.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMG_FIELD_NUMBER = 3;
    private volatile Object img_;
    /**
     * <code>optional string img = 3;</code>
     */
    public String getImg() {
      Object ref = img_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        img_ = s;
        return s;
      }
    }
    /**
     * <code>optional string img = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImgBytes() {
      Object ref = img_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        img_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 4;
    private volatile Object mobile_;
    /**
     * <code>optional string mobile = 4;</code>
     */
    public String getMobile() {
      Object ref = mobile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mobile = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEAT_FIELD_NUMBER = 7;
    private long createAt_;
    /**
     * <code>optional uint64 createAt = 7;</code>
     */
    public long getCreateAt() {
      return createAt_;
    }

    public static final int COMMUNITYID_FIELD_NUMBER = 5;
    private int communityId_;
    /**
     * <code>optional int32 communityId = 5;</code>
     */
    public int getCommunityId() {
      return communityId_;
    }

    public static final int COMMUNITYNAME_FIELD_NUMBER = 6;
    private volatile Object communityName_;
    /**
     * <code>optional string communityName = 6;</code>
     */
    public String getCommunityName() {
      Object ref = communityName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        communityName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string communityName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCommunityNameBytes() {
      Object ref = communityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        communityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!getImgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, img_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, mobile_);
      }
      if (communityId_ != 0) {
        output.writeInt32(5, communityId_);
      }
      if (!getCommunityNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, communityName_);
      }
      if (createAt_ != 0L) {
        output.writeUInt64(7, createAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!getImgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, img_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, mobile_);
      }
      if (communityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, communityId_);
      }
      if (!getCommunityNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, communityName_);
      }
      if (createAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, createAt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.User)
        UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserProto.internal_static_tutorial_User_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserProto.internal_static_tutorial_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                User.class, Builder.class);
      }

      // Construct using com.quxionglie.rpc.protobuf3.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        img_ = "";

        mobile_ = "";

        createAt_ = 0L;

        communityId_ = 0;

        communityName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserProto.internal_static_tutorial_User_descriptor;
      }

      public User getDefaultInstanceForType() {
        return User.getDefaultInstance();
      }

      public User build() {
        User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public User buildPartial() {
        User result = new User(this);
        result.id_ = id_;
        result.name_ = name_;
        result.img_ = img_;
        result.mobile_ = mobile_;
        result.createAt_ = createAt_;
        result.communityId_ = communityId_;
        result.communityName_ = communityName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof User) {
          return mergeFrom((User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(User other) {
        if (other == User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getImg().isEmpty()) {
          img_ = other.img_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (other.getCreateAt() != 0L) {
          setCreateAt(other.getCreateAt());
        }
        if (other.getCommunityId() != 0) {
          setCommunityId(other.getCommunityId());
        }
        if (!other.getCommunityName().isEmpty()) {
          communityName_ = other.communityName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object img_ = "";
      /**
       * <code>optional string img = 3;</code>
       */
      public String getImg() {
        Object ref = img_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          img_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string img = 3;</code>
       */
      public com.google.protobuf.ByteString
          getImgBytes() {
        Object ref = img_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          img_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string img = 3;</code>
       */
      public Builder setImg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        img_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string img = 3;</code>
       */
      public Builder clearImg() {
        
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string img = 3;</code>
       */
      public Builder setImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        img_ = value;
        onChanged();
        return this;
      }

      private Object mobile_ = "";
      /**
       * <code>optional string mobile = 4;</code>
       */
      public String getMobile() {
        Object ref = mobile_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public Builder setMobile(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }

      private long createAt_ ;
      /**
       * <code>optional uint64 createAt = 7;</code>
       */
      public long getCreateAt() {
        return createAt_;
      }
      /**
       * <code>optional uint64 createAt = 7;</code>
       */
      public Builder setCreateAt(long value) {
        
        createAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 createAt = 7;</code>
       */
      public Builder clearCreateAt() {
        
        createAt_ = 0L;
        onChanged();
        return this;
      }

      private int communityId_ ;
      /**
       * <code>optional int32 communityId = 5;</code>
       */
      public int getCommunityId() {
        return communityId_;
      }
      /**
       * <code>optional int32 communityId = 5;</code>
       */
      public Builder setCommunityId(int value) {
        
        communityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 communityId = 5;</code>
       */
      public Builder clearCommunityId() {
        
        communityId_ = 0;
        onChanged();
        return this;
      }

      private Object communityName_ = "";
      /**
       * <code>optional string communityName = 6;</code>
       */
      public String getCommunityName() {
        Object ref = communityName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          communityName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string communityName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCommunityNameBytes() {
        Object ref = communityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          communityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string communityName = 6;</code>
       */
      public Builder setCommunityName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        communityName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string communityName = 6;</code>
       */
      public Builder clearCommunityName() {
        
        communityName_ = getDefaultInstance().getCommunityName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string communityName = 6;</code>
       */
      public Builder setCommunityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        communityName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.User)
    }

    // @@protoc_insertion_point(class_scope:tutorial.User)
    private static final User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new User();
    }

    public static User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new User(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nuser.proto\022\010tutorial\"{\n\004User\022\n\n\002id\030\001 \001" +
      "(\005\022\014\n\004name\030\002 \001(\t\022\013\n\003img\030\003 \001(\t\022\016\n\006mobile\030" +
      "\004 \001(\t\022\020\n\010createAt\030\007 \001(\004\022\023\n\013communityId\030\005" +
      " \001(\005\022\025\n\rcommunityName\030\006 \001(\tB/\n\"com.quxio" +
      "nglie.rpc.protobuf3.protoB\tUserProtob\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_User_descriptor,
        new String[] { "Id", "Name", "Img", "Mobile", "CreateAt", "CommunityId", "CommunityName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
